### ISSUE TITLE
How to initialize and make the most of the available metadata

### ISSUE THREAD

**Issue by rowanwins** [rowanwins/esri-leaflet-socket#1]
So one thing I've been thinking about is how to best intiatialize the layer.

Currently a user passes the actual socket url, and if they want features to move around they need to pass in a field (eg BusNo) to use as the unique id 

```
  var buses = L.esri.socketFeatureLayer({
        url: 'wss://geoeventsample3.esri.com:8443/arcgis/ws/services/SeattleBus/StreamServer',
        idField: 'BusNo'
    }).addTo(map);

    buses.subscribe();
```

Perhaps it would make more sense for the url to reference the server endpoint and it's metadata eg
`https://geoeventsample3.esri.com:6443/arcgis/rest/services/SeattleBus/StreamServer`
For example if you return the json of this endpoint you can find out the socket URL and the unique id field. This would also be more consistent with how the rest of esri leaflet operates.

My biggest concern with shifting to this approach is how to manage the initial request to get the metadata... Does a request to this page become part of the subscribe method of the plugin?  Or does it go in the initialize method so it's only called once?

Any thoughts @jgravois

**Comment by jgravois** [comment]
> Does a request to this page become part of the subscribe method of the plugin? Or does it go in the initialize method so it's only called once?

i'd recommend following the pattern in L.esri.tiledMapLayer and firing your metadata request inside [`onAdd()`](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/TiledMapLayer.js#L104-L129).

also, this is pure peanut gallery, but i think it'd make sense to make your `subscribe()` function private and use it internally to connect to the web socket as soon as developers add the layer to the map.

you could do the same and `_unsubscribe()` programmatically if/when they remove the layer.

**Comment by rowanwins** [comment]
Thanks for the suggestions @jgravois - they make sense so I'll have a crack at incorporating them.

**Comment by rowanwins** [comment]
Thanks @jgravois I've incorporated those changes and its working nicely I think although always happy for feedback

**Comment by jgravois** [comment]
cool!
