### ISSUE TITLE
tag a release?

### ISSUE THREAD

**Issue by jgravois** [rowanwins/esri-leaflet-socket#2]
your call, but i'd recommend tagging `1.0.0` and skipping the beta/rc stuff.

**Comment by rowanwins** [comment]
In Australia we'd call you an 'ideas man' @jgravois - see this cultural reference  https://youtu.be/4Lrbw4-vkFM

**Comment by jgravois** [comment]
as long as they don't put in an airport next to your house...

**Comment by rowanwins** [comment]
Done it I think, and I've even managed to get it [published on npm](https://www.npmjs.com/package/esri-leaflet-stream)!
